import { createFileRoute, Link, notFound, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Copy, GripVertical, ImagePlus, LoaderCircle, Mail, MapPin, Phone, Share2, Trash2, Upload, X } from "lucide-react";
import { useEffect, useRef, useState, type ChangeEvent, type DragEvent } from "react";
import QRCode from "qrcode";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { InvitationRenderer } from "@/components/invitations/InvitationRenderer";
import { publishInvitation, uploadWeddingImage } from "@/lib/invitations.functions";
import { sampleInvitation, TEMPLATE_IDS, templateMeta, type TemplateId, type WeddingInvitation } from "@/lib/invitation";

export const Route = createFileRoute("/create/$templateId")({
  beforeLoad: ({ params }) => { if (!TEMPLATE_IDS.includes(params.templateId as TemplateId)) throw notFound(); },
  head: ({ params }) => ({ meta: [
    { title: `Customize ${templateMeta[params.templateId as TemplateId]?.name ?? "Invitation"} — Tizita` }, { name: "description", content: "Add your names, wedding details, story, and photos to create your invitation." },
    { property: "og:title", content: "Create Your Ethiopian Wedding Invitation — Tizita" }, { property: "og:description", content: "Customize and publish your own beautiful bilingual wedding invitation." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Builder,
});
const steps = ["Couple", "Details", "Story", "Photos", "RSVP", "Preview"];
function Builder() {
  const { templateId } = Route.useParams(); const id = templateId as TemplateId; const navigate = useNavigate();
  const [step,setStep]=useState(0); const [saving,setSaving]=useState(false); const [success,setSuccess]=useState<string>(); const [qr,setQr]=useState<string>(); const [drag,setDrag]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
  const storageKey=`tizita-draft-${id}`;
  const [data,setData]=useState<WeddingInvitation>(()=>({...sampleInvitation,templateId:id,brideName:"",groomName:"",brideNameAm:"",groomNameAm:"",primaryPhotoUrl:"",galleryImages:[]}));
  useEffect(()=>{ const saved=localStorage.getItem(storageKey); if(saved){try{setData(JSON.parse(saved))}catch{}} },[storageKey]);
  useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify(data))},[data,storageKey]);
  const update=(field:keyof WeddingInvitation,value:unknown)=>setData(current=>({...current,[field]:value}));
  const next=()=>{if(step===0&&(!data.brideName.trim()||!data.groomName.trim())){toast.error("Please add the couple's names.");return} if(step===1&&!data.weddingDate){toast.error("Please select your wedding date.");return} setStep(Math.min(5,step+1));};
  const handleFiles=async(files:FileList|File[])=>{const selected=Array.from(files); for(const file of selected){if(!["image/jpeg","image/png","image/webp"].includes(file.type)){toast.error(`${file.name} is not a supported image.`);continue} if(file.size>10*1024*1024){toast.error("Your image is too large. Please upload an image under 10MB.");continue} setSaving(true); try{const base64=await fileToBase64(file); const result=await uploadWeddingImage({data:{name:file.name,mimeType:file.type as "image/jpeg"|"image/png"|"image/webp",base64}}); setData(current=>current.primaryPhotoUrl?{...current,galleryImages:[...current.galleryImages,result.url]}:{...current,primaryPhotoUrl:result.url}); toast.success(`${file.name} uploaded`)}catch(error){toast.error(error instanceof Error?error.message:"Image upload failed")}finally{setSaving(false)}}};
  const publish=async()=>{setSaving(true);try{const result=await publishInvitation({data}); const url=`${window.location.origin}/invite/${result.slug}`; setSuccess(url); setQr(await QRCode.toDataURL(url,{width:720,margin:2,color:{dark:"#2a1714",light:"#fffaf2"}})); localStorage.removeItem(storageKey)}catch(error){toast.error(error instanceof Error?error.message:"Invitation could not be created")}finally{setSaving(false)}};
  if(success) return <Success url={success} qr={qr}/>;
  return <main className="builder-page"><header className="builder-header"><Button asChild variant="ghost"><Link to="/"><ArrowLeft/> Exit</Link></Button><div className="builder-brand"><span>ትዝታ</span><strong>{templateMeta[id].name}</strong></div><span className="autosave"><Check/> Draft saved</span></header>
    <div className="builder-progress"><div className="progress-top"><span>Step {step+1} of 6</span><strong>{steps[step]}</strong></div><div className="progress-track"><i style={{width:`${((step+1)/6)*100}%`}}/></div><div className="progress-labels">{steps.map((name,index)=><button key={name} className={index<=step?"active":""} onClick={()=>setStep(index)}><span>{index<step?<Check/>:index+1}</span>{name}</button>)}</div></div>
    <div className="builder-workspace"><section className="builder-form"><div className="form-heading"><p>{String(step+1).padStart(2,"0")} / 06</p><h1>{["Tell us your names","When & where","Share your story","Add your moments","Guest replies","One last look"][step]}</h1><span>{["The names at the heart of your invitation.","Everything your guests need to arrive with ease.","A few words that sound unmistakably like you.","Choose one main portrait and your favorite memories.","Make it easy for your people to say yes.","Your invitation is ready to become real."][step]}</span></div>
      {step===0&&<div className="form-grid"><Field label="Bride's Name"><Input value={data.brideName} onChange={e=>update("brideName",e.target.value)} placeholder="Hana Tesfaye" maxLength={100}/></Field><Field label="Groom's Name"><Input value={data.groomName} onChange={e=>update("groomName",e.target.value)} placeholder="Abebe Mekonnen" maxLength={100}/></Field><Field label="Bride's Name in Amharic"><Input lang="am" value={data.brideNameAm} onChange={e=>update("brideNameAm",e.target.value)} placeholder="ሀና ተስፋዬ" maxLength={100}/></Field><Field label="Groom's Name in Amharic"><Input lang="am" value={data.groomNameAm} onChange={e=>update("groomNameAm",e.target.value)} placeholder="አቤቤ መኮንን" maxLength={100}/></Field></div>}
      {step===1&&<div className="form-grid"><Field label="Wedding date"><Input type="date" value={data.weddingDate} onChange={e=>update("weddingDate",e.target.value)}/></Field><Field label="Wedding time"><Input type="time" value={data.weddingTime} onChange={e=>update("weddingTime",e.target.value)}/></Field><Field label="Ceremony type"><Input value={data.ceremonyType} onChange={e=>update("ceremonyType",e.target.value)} placeholder="Ceremony & reception"/></Field><Field label="Venue"><Input value={data.venue} onChange={e=>update("venue",e.target.value)} placeholder="Hyatt Regency Addis Ababa"/></Field><Field label="Venue in Amharic"><Input lang="am" value={data.venueAm} onChange={e=>update("venueAm",e.target.value)} placeholder="ሃያት ሪጀንሲ አዲስ አበባ"/></Field><Field label="Address"><Input value={data.address} onChange={e=>update("address",e.target.value)} placeholder="Meskel Square, Addis Ababa"/></Field><Field label="Address in Amharic"><Input lang="am" value={data.addressAm} onChange={e=>update("addressAm",e.target.value)} placeholder="መስቀል አደባባይ፣ አዲስ አበባ"/></Field><Field label="Google Maps link"><Input type="url" value={data.mapsUrl} onChange={e=>update("mapsUrl",e.target.value)} placeholder="https://maps.google.com/..."/></Field></div>}
      {step===2&&<div className="form-stack"><Field label="How you met"><Textarea value={data.howWeMet} onChange={e=>update("howWeMet",e.target.value)} placeholder="A chance meeting over coffee..." maxLength={2000}/></Field><Field label="Your love story"><Textarea className="large" value={data.story} onChange={e=>update("story",e.target.value)} placeholder="Tell your guests about the path that brought you here..." maxLength={5000}/></Field><Field label="Your story in Amharic (optional)"><Textarea lang="am" value={data.storyAm} onChange={e=>update("storyAm",e.target.value)} placeholder="የፍቅር ታሪካችሁን በአማርኛ ያካፍሉ..." maxLength={5000}/></Field></div>}
      {step===3&&<div><div className={`dropzone ${drag?"dragging":""}`} onDragOver={(e)=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={(e:DragEvent)=>{e.preventDefault();setDrag(false);void handleFiles(e.dataTransfer.files)}}><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={(e:ChangeEvent<HTMLInputElement>)=>e.target.files&&void handleFiles(e.target.files)}/>{saving?<LoaderCircle className="spin"/>:<Upload/>}<h3>Drop your wedding photos here</h3><p>JPG, PNG or WebP · maximum 10MB each</p><Button type="button" variant="outline" onClick={()=>fileRef.current?.click()}>Choose photos</Button></div><div className="photo-list">{data.primaryPhotoUrl&&<PhotoRow image={data.primaryPhotoUrl} label="Main couple photo" onDelete={()=>update("primaryPhotoUrl","")}/>} {data.galleryImages.map((image,index)=><PhotoRow key={image} image={image} label={`Gallery photo ${index+1}`} onDelete={()=>update("galleryImages",data.galleryImages.filter((_,i)=>i!==index))}/>)}</div></div>}
      {step===4&&<div className="form-stack"><div className="rsvp-toggle"><div><h3>Enable RSVP</h3><p>Show reply details on your invitation.</p></div><Switch checked={data.rsvpEnabled} onCheckedChange={value=>update("rsvpEnabled",value)}/></div>{data.rsvpEnabled&&<div className="form-grid"><Field label="RSVP deadline"><Input type="date" value={data.rsvpDeadline} onChange={e=>update("rsvpDeadline",e.target.value)}/></Field><Field label="Contact phone"><Input type="tel" value={data.phone} onChange={e=>update("phone",e.target.value)} placeholder="+251 911 234 567"/></Field><Field label="Contact email"><Input type="email" value={data.email} onChange={e=>update("email",e.target.value)} placeholder="hello@example.com"/></Field><Field label="Closing message"><Textarea value={data.customMessage} onChange={e=>update("customMessage",e.target.value)} placeholder="With joyful hearts..."/></Field></div>}</div>}
      {step===5&&<div className="review-list"><Review icon={HeartIcon} label="Couple" value={`${data.brideName} & ${data.groomName}`} onEdit={()=>setStep(0)}/><Review icon={CalendarDays} label="Wedding" value={`${data.weddingDate} · ${data.weddingTime}`} onEdit={()=>setStep(1)}/><Review icon={MapPin} label="Venue" value={data.venue||"Not added"} onEdit={()=>setStep(1)}/><Review icon={ImagePlus} label="Photos" value={`${(data.primaryPhotoUrl?1:0)+data.galleryImages.length} uploaded`} onEdit={()=>setStep(3)}/><Review icon={Phone} label="RSVP" value={data.rsvpEnabled?(data.phone||data.email||"Enabled"):"Disabled"} onEdit={()=>setStep(4)}/></div>}
      <div className="form-navigation"><Button variant="outline" disabled={step===0||saving} onClick={()=>setStep(step-1)}><ArrowLeft/>Back</Button>{step<5?<Button onClick={next}>Continue<ArrowRight/></Button>:<Button onClick={publish} disabled={saving}>{saving?<LoaderCircle className="spin"/>:<Share2/>}Generate My Invitation</Button>}</div>
    </section><aside className="live-preview"><div className="preview-label"><div><span>LIVE PREVIEW</span><i/></div><strong>{templateMeta[id].name}</strong></div><div className="phone-preview"><InvitationRenderer invitation={data} compact/></div></aside></div></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <Label className="field"><span>{label}</span>{children}</Label>}
function PhotoRow({image,label,onDelete}:{image:string;label:string;onDelete:()=>void}){return <div className="photo-row"><GripVertical/><img src={image} alt="Upload preview"/><span>{label}</span><button onClick={onDelete} aria-label={`Remove ${label}`}><Trash2/></button></div>}
function Review({icon:Icon,label,value,onEdit}:{icon:typeof CalendarDays;label:string;value:string;onEdit:()=>void}){return <div className="review-item"><Icon/><div><span>{label}</span><strong>{value}</strong></div><button onClick={onEdit}>Edit</button></div>}
function HeartIcon(){return <span className="review-heart">♥</span>}
function fileToBase64(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=reject;reader.readAsDataURL(file)})}
function Success({url,qr}:{url:string;qr?:string}){const copy=()=>navigator.clipboard.writeText(url).then(()=>toast.success("Invitation link copied"));return <main className="success-page"><div className="success-mark"><Check/></div><p>READY TO SHARE</p><h1>Your Invitation<br/><em>Is Ready!</em></h1><span>Your wedding invitation has been created. Share it with everyone you love.</span><div className="link-box"><div><small>Your Invitation Link</small><strong>{url}</strong></div><button onClick={copy} aria-label="Copy invitation link"><Copy/></button></div><div className="success-actions"><Button asChild size="lg"><a href={url}>Open Invitation</a></Button><Button variant="outline" size="lg" onClick={copy}><Copy/>Copy Link</Button></div><div className="share-row"><a href={`https://wa.me/?text=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer">WhatsApp</a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer">Facebook</a><a href={`https://t.me/share/url?url=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer">Telegram</a>{qr&&<a href={qr} download="wedding-invitation-qr.png">Download QR</a>}</div>{qr&&<img className="qr-code" src={qr} alt="Invitation QR code"/>}<Button asChild variant="ghost"><Link to="/">Return to Tizita</Link></Button></main>}
